// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/assessment/asrs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/asrs">> = Specific
  const handler = {} as typeof import("../../app/assessment/asrs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/asrs/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/asrs/results">> = Specific
  const handler = {} as typeof import("../../app/assessment/asrs/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/comorbidity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/comorbidity">> = Specific
  const handler = {} as typeof import("../../app/assessment/comorbidity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/family">> = Specific
  const handler = {} as typeof import("../../app/assessment/family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/history">> = Specific
  const handler = {} as typeof import("../../app/assessment/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/impact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/impact">> = Specific
  const handler = {} as typeof import("../../app/assessment/impact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/review">> = Specific
  const handler = {} as typeof import("../../app/assessment/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assessment/start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment/start">> = Specific
  const handler = {} as typeof import("../../app/assessment/start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/asrs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/asrs">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/asrs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/comorbidity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/comorbidity">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/comorbidity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/complete">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/family/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/family">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/family/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/history">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessment/impact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/impact">> = Specific
  const handler = {} as typeof import("../../app/api/assessment/impact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
